Сделал разметку страниц
htmlacademy-htmlcss/1810205-nerds-31 pull request #2
Opened 2021-05-25 15:35 UTC by ValeraAvdeiko

Сделал грубую разметку страниц, осталось много вопросов. Часть добавил в скрытые комментарии

2021-05-26 13:17 UTC, Dima-Dim requested changes
Нарезку изображений вы пока не проходили, по этому делать её ну нежно.
Задания нужно выполнять в соответствии с описанием. Сейчас это должна быть только одна главная страница. Можно добавить так же blank.html

По названиям файлов https://up.htmlacademy.ru/htmlcss/31/criteries

2021-05-26 13:17 UTC, Dima-Dim commented on img/illustration-3 1.svg
> +<image id="image0" width="300" height="146" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACSCAIAAABwqGCTAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZ
Это не svg.

2021-05-26 13:17 UTC, Dima-Dim commented on index.html
> +        <a>
В теге ul не может быть ничего кроме тегов li. Для того чтобы не допускать таких ошибок нужно проверяться https://validator.w3.org/nu/

2021-05-26 13:17 UTC, Dima-Dim commented on index.html
> +        <li><a href="blank.html">СТУДИЯ</a></li>
Слова пишем как в обычных предложениях, стилизацию будем выполнять позже.

2021-05-26 13:17 UTC, Dima-Dim commented on index.html
> +      <!--Не знаю как правильно поступить со слайдером и стоит ли для карусели использовать figure-->
Слайдер очень похож на список элементов. Тег figure использовать не обязательно.

2021-05-26 13:17 UTC, Dima-Dim commented on index.html
> +        <button type="button" disabled></button>
Очень похоже на список.

2021-05-26 13:17 UTC, Dima-Dim commented on index.html
> +            <p>Мир никогда не будет прежним<br>после того как увидит ваш сайт!</p>
br это про стилизацию, ею мы займёмся позже.

2021-05-26 13:17 UTC, Dima-Dim commented on index.html
> +          <li>Мобильных приложений для iOS и Android
Не закрыт li

2021-05-26 13:17 UTC, Dima-Dim commented on index.html
> +          <li><h4>146<sup>%</sup></h4>
h4 здесь перебор.

2021-05-27 17:41 UTC, ValeraAvdeiko commented
Внес все изменения.

2021-05-27 17:41 UTC, closed without merging