Сделал разметку страниц
htmlacademy-htmlcss/1810205-nerds-31 pull request #3
Opened 2021-05-27 17:49 UTC by ValeraAvdeiko

Внес все изменения из ваших комментариев

2021-05-28 10:29 UTC, Dima-Dim requested changes
Не забываем пред отправкой проверять html код валидатором https://validator.w3.org/nu/
Отправляем на проверку только то что требуется по заданию :)

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +        <a href="index.html">
Лого я всё же рекомендовал бы вынести из списка. Не похож он на все остальные пункты ни визуально, ни логически.

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +        <li><a href="blank.html">СТУДИЯ</a></li>
Слова пишем как в обычных предложениях. Стилизацию будем делать позже с помощью css.

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +      <section>
Не нужно делать section для одного лишь заголовка.

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +            <!--НЕ знаю как сделать ползунок-->
Сделаете после лайва про декоративные элементы.

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +      <!--Кнопка не работает?!-->
Пока нам достаточно того что это тег button внутри тега form с типом submit.

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +        <form action="ttps://echo.htmlacademy.ru" method="post">
`ttps` -> `https` и заработает :)

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +        <!--Не знаю как правильно сделать сортировку по возрастанию и убыванию стрелочками, пока вставил только иконки-->
Можно будет вернуться к этому месте после лайвов про декоративные элементы и доступность.

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +            <a href="catalog.html">
О том что это ссылка нигде ничего нет. Есть только https://up.htmlacademy.ru/htmlcss/31/project/nerds#nerds-3-10 и это у тебя сделано ниже.

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +          <li><button type="button">Следующая</button><li>
Лучше тоже ссылка.

2021-05-28 10:29 UTC, Dima-Dim commented on catalog.html
> +      <uL>
`uL` -> `ul`

2021-05-28 10:29 UTC, Dima-Dim commented on img/illustration-2 1.svg
> +<image id="image0" width="300" height="146" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACSCAIAAABwqGCTAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZ
Это не svg. Предлагаю сейчас удалить файлы таких сомнительных изображений и вернуться к ним в задании на графику.

2021-05-28 10:29 UTC, Dima-Dim commented on index.html
> +      <!--Не знаю как правильно поступить со слайдером и стоит ли для карусели использовать figure-->
Слайдер это список слайдов, так что лучше использовать для них ul, figure использовать не нужно.

2021-05-28 10:29 UTC, Dima-Dim commented on index.html
> +        <button type="button" disabled></button>
Этот набор кнопок похож на список.

2021-05-28 10:29 UTC, Dima-Dim commented on index.html
> +          <li>Мобильных приложений для iOS и Android
Не закрытый li

2021-05-28 10:29 UTC, Dima-Dim commented on index.html
> +          <li><h4>146<sup>%</sup></h4>
h4 здесь перебор.

2021-05-28 10:29 UTC, Dima-Dim commented on index.html
> +      <section class="companies">
Не нужно настолько далеко бежать вперёд и расставлять классы.

2021-05-28 10:29 UTC, Dima-Dim commented on index.html
> +      <uL>
Тоже опечатка в теге.

2021-05-28 10:29 UTC, Dima-Dim commented on index.html
> +        <p><label for="form message">Текст письма:</label>
Все остальные поля формы не `p`, а это `p`? :)

2021-05-29 12:56 UTC, ValeraAvdeiko commented on catalog.html
> +        <a href="index.html">
Поправил и в каталоге и в индексе

2021-05-29 12:57 UTC, ValeraAvdeiko commented on catalog.html
> +        <li><a href="blank.html">СТУДИЯ</a></li>
Забыл изменить и сделать как в индексе, поправил.

2021-05-29 13:09 UTC, closed without merging

2021-05-29 13:09 UTC, ValeraAvdeiko commented
Внес изменения в каталог